apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: LoadBalancer
  selector:
    app: php
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql-connection
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  

      
      
 